In [3]:
import numpy as np
import tensorflow as tf
print(tf.__version__)

1.8.0


### https://www.tensorflow.org/api_docs/python/tf/split

In [5]:
data = np.array([[0.1, 0.2, 0.3], 
                 [0.4, 0.5, 0.6], 
                 [0.7, 0.8, 0.9], 
                 [0.1, 0.2, 0.3]])
print(data.shape)
print(data)

(4, 3)
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]
 [0.1 0.2 0.3]]


In [6]:
W_init = np.array([[1, 2, 1],
                   [3, 4, 3], 
                   [2, 1, 2]], dtype=float)
b_init = np.array([2,3], dtype=float)

In [7]:
W = tf.Variable(W_init, dtype=tf.float32)

In [48]:
X_i = tf.placeholder(tf.float32, [None, 3], name="x")
output_i = tf.sigmoid(tf.matmul(X_i, W))
grad_i = tf.gradients(output_i, W)

sess = tf.Session()
with sess.graph.as_default():
    sess.run(tf.global_variables_initializer())

    for i in range(len(data)):
#         print(data[i])
        x = data[i].reshape(1, len(data[i]))
#         print(x)
#         print("x shape", x.shape)
        output_i_val, grad_i_val = sess.run([output_i, grad_i], feed_dict={X_i: x})
        print("output", i, output_i_val)
        print("grad", i, grad_i_val)

output 0 [[0.785835 0.785835 0.785835]]
grad 0 [array([[0.01682983, 0.01682983, 0.01682983],
       [0.03365967, 0.03365967, 0.03365967],
       [0.0504895 , 0.0504895 , 0.0504895 ]], dtype=float32)]
output 1 [[0.9568927 0.9677046 0.9568927]]
grad 1 [array([[0.01649961, 0.01250097, 0.01649961],
       [0.02062452, 0.01562621, 0.02062452],
       [0.02474942, 0.01875145, 0.02474942]], dtype=float32)]
output 2 [[0.9926085 0.9959299 0.9926085]]
grad 2 [array([[0.00513581, 0.00283748, 0.00513581],
       [0.0058695 , 0.00324283, 0.0058695 ],
       [0.00660319, 0.00364818, 0.00660319]], dtype=float32)]
output 3 [[0.785835 0.785835 0.785835]]
grad 3 [array([[0.01682983, 0.01682983, 0.01682983],
       [0.03365967, 0.03365967, 0.03365967],
       [0.0504895 , 0.0504895 , 0.0504895 ]], dtype=float32)]


In [76]:
X = tf.placeholder(tf.float32, [None, 3], name="x")
output = tf.sigmoid(tf.matmul(X, W))
print("output.shape:", output.shape)
grad = tf.gradients(output, W)

sess = tf.Session()
with sess.graph.as_default():
    sess.run(tf.global_variables_initializer())

    output_val, grad_val = sess.run([output, grad], feed_dict={X: data})
    print("output_val", output_val)
    print("grad_val", grad_val)

output.shape: (?, 3)
output_val [[0.785835  0.785835  0.785835 ]
 [0.9568927 0.9677046 0.9568927]
 [0.9926085 0.9959299 0.9926085]
 [0.785835  0.785835  0.785835 ]]
grad_val [array([[0.0552951 , 0.04899811, 0.0552951 ],
       [0.09381335, 0.08618837, 0.09381335],
       [0.13233162, 0.12337865, 0.13233162]], dtype=float32)]


In [60]:
def func(x):
    return tf.sigmoid(tf.matmul(x[0], x[1]))

In [81]:
X = tf.placeholder(tf.float32, [None, 3], name="x")

W = tf.Variable(np_W, dtype=tf.float32)
b = tf.Variable(np_b, dtype=tf.float32)

X_splited = tf.split(X, num_or_size_splits=4)
# weight_copies = [tf.identity(W) for x in X_splited]
weight_copies = [W for _ in range(len(X_splited))]
print("type(X_splited)", type(X_splited))
print("type(weight_copies[0])", type(weight_copies[0]))
print("weight_copies[0]", weight_copies[0])
# elems = [z for z in zip(examples, weight_copies)]
# print(len(elems[0]))
output = tf.stack([func(z) for z in zip(X_splited, weight_copies)])
print("type(output):", type(output))
print("output.shape:", output.shape)
print("output[0].shape:", output[0].shape)
per_example_gradients = tf.gradients(output, weight_copies)
print("type(per_example_gradients):", type(per_example_gradients))
print("len(per_example_gradients):", len(per_example_gradients))
print("per_example_gradients[0].shape:", per_example_gradients[0].shape)

# # # grads_W, grads_b = tf.gradients(U, xs=[W, b])

sess = tf.Session()
with sess.graph.as_default():
    sess.run(tf.global_variables_initializer())
        # grads_w_i, grads_b_i = sess.run([grads_W, grads_b], feed_dict={X: data})
        # print(grads_w_i.shape)
        # print(grads_w_i)
        # print(grads_b_i.shape)
        # print(grads_b_i)

        # grads_w_i = sess.run(per_example_gradients, feed_dict={X: data})
        # print(grads_w_i.shape)

        # elems_1 = sess.run(elems, feed_dict={X: data})
        # print(elems_1[0])
        #
    output_1, per_example_gradients_1 = sess.run([output, per_example_gradients], feed_dict={X: data})
    print(output_1.shape)
    print(output_1)
    print(per_example_gradients_1)

type(X_splited) <class 'list'>
type(weight_copies[0]) <class 'tensorflow.python.ops.variables.Variable'>
weight_copies[0] <tf.Variable 'Variable_60:0' shape=(3, 3) dtype=float32_ref>
type(output): <class 'tensorflow.python.framework.ops.Tensor'>
output.shape: (4, ?, 3)
output[0].shape: (?, 3)
type(per_example_gradients): <class 'list'>
len(per_example_gradients): 4
per_example_gradients[0].shape: (3, 3)
(4, 1, 3)
[[[0.785835  0.785835  0.785835 ]]

 [[0.9568927 0.9677046 0.9568927]]

 [[0.9926085 0.9959299 0.9926085]]

 [[0.785835  0.785835  0.785835 ]]]
[array([[0.0552951 , 0.04899811, 0.0552951 ],
       [0.09381335, 0.08618837, 0.09381335],
       [0.13233162, 0.12337865, 0.13233162]], dtype=float32), array([[0.0552951 , 0.04899811, 0.0552951 ],
       [0.09381335, 0.08618837, 0.09381335],
       [0.13233162, 0.12337865, 0.13233162]], dtype=float32), array([[0.0552951 , 0.04899811, 0.0552951 ],
       [0.09381335, 0.08618837, 0.09381335],
       [0.13233162, 0.12337865, 0.13233162]]