# One Hot Encoding

### One-Hot Encoding With Scikit-Learn
* Transforming your labels into one-hot encoded vectors is pretty simple with scikit-learn using <b style='color: red'>LabelBinarizer</b>. 

In [5]:
import numpy as np
from sklearn import preprocessing

labels = np.array([1,5,3,2,1,4,2,1,3])

# Create the encoder
lb = preprocessing.LabelBinarizer()

# Here the encoder finds the classes and assigns one-hot vectors 
lb.fit(labels)

# And finally, transform the labels into one-hot encoded vectors
one_hot = lb.transform(labels)
print(one_hot)

[[1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]]


### One-Hot Encoding from scratch

In [11]:
# Get number of samples
N = len(labels)

# Get number of classes
K = len(set(labels))

# Initialize one_hot_encoding with zeros
ind = np.zeros((N, K))

# start encoding
for i in range(N):
    ind[i, labels[i] - 1] = 1
    
print(ind)

[[ 1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]]
