In [6]:
import pandas as pd
import numpy as np
import math as ma

In [2]:
k = np.exp(1)
arr = np.arange(2)
print(arr)
v = np.exp(arr)

print(k)
print(v)

[0 1]
2.71828182846
[ 1.          2.71828183]


In [3]:
np.zeros((3, 2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [4]:
y = np.arange(0,50)
b=y>20
b

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True], dtype=bool)

In [5]:
a = np.array([[1, 2]])

a.shape

(1, 2)

In [10]:
def relu(A):
    print(A>0)
    return A * (A > 0)

In [11]:
A = np.random.randn(2,3)
print(A)

[[-0.83836198 -0.6737727  -0.27144729]
 [ 0.85769762  0.25988196 -0.69863121]]


In [12]:
print(relu(A))

[[False False False]
 [ True  True False]]
[[-0.         -0.         -0.        ]
 [ 0.85769762  0.25988196 -0.        ]]


In [18]:
False * -0.9

-0.0

In [22]:
C = np.random.randn(2,3)
b = np.random.randn(3)
print(C)
print(b)
print(C+b)

[[ 1.25341115 -0.25290486  0.47194653]
 [ 0.50426282 -0.55477703  0.02676074]]
[-0.6862659   0.97197352 -0.36776327]
[[ 0.56714525  0.71906866  0.10418327]
 [-0.18200308  0.41719649 -0.34100253]]


In [26]:
A = np.array([[1,0],[0,1]])
P = np.array([[0.7,0.3],[0.8,0.2]])

print(A)
print(P)
print(A*P)
print((A*P).sum())

[[1 0]
 [0 1]]
[[ 0.7  0.3]
 [ 0.8  0.2]]
[[ 0.7  0. ]
 [ 0.   0.2]]
0.9


In [38]:
def softmax(A):
    expA = np.exp(A)
    return expA / expA.sum(axis=1, keepdims=True)

X = np.array([[1,2]])

W1 = np.array([[1,1], [1,0]])
W2 = np.array([[0,1], [1,1]])

Z = X.dot(W1)
Z = np.tanh(Z)

Y = Z.dot(W2)
print(softmax(Y))

[[ 0.26991483  0.73008517]]


In [3]:
5//2

2

In [7]:
ma.ceil( float(5) / float(2))

3