In [2]:
import numpy as np

## Arrays

* A numpy array is a grid of values, all of the same type, and is indexed by a tuple of integers. 
    * Normally, the indexes are nonnegative integers. But indexes can be negative integers which means indexes in reverse order.
* The number of dimensions is the rank of the array; 
* the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from <b>nested Python lists</b>, and access elements using square brackets:

In [3]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2], a[-2])   # Prints "1 2 3 2"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3 2
[5 2 3]
(2, 3)
1 2 4


Numpy also provides many functions to create arrays:

In [13]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[7 7]
 [7 7]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.14315191  0.40100815]
 [ 0.57324703  0.24281058]]


You can read about other methods of array creation in the [documentation](https://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation).

## Arrays vs List

In [8]:
L = [1, 2, 3]
A = np.array([1, 2, 3])

print(type(L))
print(type(A))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
L.append(5)
print(L)

[1, 2, 3, 5]


In [10]:
#  There is not 'append' method on numpy array
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [11]:
L = L + [9]
L

[1, 2, 3, 5, 9]

In [14]:
A = A + [4, 5]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

The error message shows that the plus sign with numpy array does something involves broadcast, which we will talk about later.

It does not concatenate two arrays like what plus sign with lists does.

In [16]:
print(A)
print(A + A)

[1 2 3]
[2 4 6]


> A '+' sign with lists does concatenation but the '+' sign with an numpy array does vector addition. If you have a matrix, which is two dimentional array, the '+' would do a matrix addtion. Generally speaking, what '+' does with numpy is `element-wise` addtion. This aslo applies to '-', '\', '*', square and many others.

What would happen if we multiply an array and list with a scalar value respectively

In [19]:
print(2 * A)

[2 4 6]


In [18]:
print(2 * L)

[1, 2, 3, 5, 9, 1, 2, 3, 5, 9]


If you did want to multiply every element of the list, you would have to do a for loop and go through each element individually. 

In [21]:
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [22]:
A**2

array([1, 4, 9])

### np.append() ###
You can use [np.append()](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.append.html) function to concatenate arrays. You should be carefull that you may need to tell numpy which dimension you want two arrays to concatenate.

In [31]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9]])
print(array1.shape)
print(array2.shape)
array3 = np.append(array1, array2, axis=0)
print(array3.shape)
print(array3)

(2, 3)
(1, 3)
(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


The `axis` along which values are appended. If axis is not given, both arr and values are flattened before use.

In [32]:
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

****

## Array indexing

Numpy offers several ways to index into arrays.

<b>Slicing</b>: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

NOTE that <b>A slice of an array is a view into the same data, so modifying it
will modify the original array.</b>

In [7]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# b = a[:2]
# print(b)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[2 3]
 [6 7]]
2
77


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing.
* Two ways of accessing the data in the middle row of the array.
    * Mixing integer indexing with slices yields an array of lower rank,
    * while using only slices yields an array of the same rank as the original array

In [8]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


<b>Integer array indexing</b>: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [13]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)
# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix.
* We frequently use this trick to compute cross entropy where we need to choose a probability from the probability distribution over output for each input sample.

In [15]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
c = a[np.arange(4), b]
print(c)  # Prints "[ 1  6  7 11]"
print(c.shape)
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
(4,)
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


<b>Boolean array indexing</b>: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [16]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the [documentation](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).

## DataTypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [18]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

x = np.array([1, 2], dtype=np.float32)   # Force a particular datatype
print(x.dtype)                         # Prints "float32"

int64
float64
int64
float32


You can read all about numpy datatypes in the [documentation](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

****

## Broadcasting

* Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.
* Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. 
    * Subject to certain constraints, the smaller array is "broadcast" across the larger array so that they have compatible shapes. 
    * roadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. 
    * There are also cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation. 
 
This [article](http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc) provides a gentle introduction and explanation to broadcasting with numerous examples ranging from simple to involved, and it also provides hints on when and when not to use broadcasting. Or, you can refer to [broadcasting document](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [25]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create a new array with the same shape and type as a given array.
                       # the 'empty' is confusing. It actually returns random values.
                       # Other similar functions:
                       # - ones_like
                       # Return an array of ones with shape and type of input.
                       # - zeros_like
                       # Return an array of zeros with shape and type of input.
                       # - empty
                       # Return a new uninitialized array.
                       # - ones
                       # Return a new array setting values to one.
                       # - zeros
                       # Return a new array setting values to zero.

# print(y) 

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix x is very large, computing an explicit loop in Python could be slow. 

Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. We could implement this approach like this:

In [29]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])


vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
            
# vv2 = np.tile(v, (4, 2))  
# print(vv2) 

y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v (NumPy will automatically do this job). Consider this version, using broadcasting:

In [60]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print("shape of x: ", x.shape)
v = np.array([1, 0, 1])
print("shape of v: ", v.shape)
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

shape of x:  (4, 3)
shape of v:  (3,)
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting: 
* this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.

### The Broadcasting Rule

> When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when 1. they are equal, or 2 one of them is 1.

* If this condition is not met, a ValueError: frames are not aligned exception is thrown indicating that the arrays have incompatible shapes. 
* The size of the result array created by broadcast operations is the maximum size along each dimension from the input arrays. 
* Note that the rule does not say anything about the two arrays needing to have the same number of dimensions.


**Examples**

For example, if you have a 256x256x3 array of RGB values, and you want to scale each color in the image by a different value, you can multiply the image by a one-dimensional array with 3 values. 

* Lining up the sizes of the trailing dimensions of these arrays 
    * The image has shape (256, 256, 3), the scale array has shape (3)
    * Right align the dimensions of the two arrays
    * according to the broadcast rule shows that they are compatible.
        * In dim 3, Image is the same as Scale, valid
        * In dim 2, Scale is empty, valid
        * In dim 1, Scale is empty, valid
    
|                 | dim 1   | dim 2   | dim 3 |
|----------------:|--------:| -------:| -----:|
|Image  (3d array)| 256     | 256     |   3   |
|Scale  (1d array)|         |         |   3   |
|Result (3d array)| 256     | 256     |   3   |


according to the broadcast rule shows that they are compatible:

In the following example, both the A and B arrays have axes with length one that are expanded to a larger size in a broadcast operation.

* Lining up the sizes of the trailing dimensions of these arrays 
    * The A array has shape (8, 1, 6, 1), the B array has shape (7, 1, 5)
    * Right align the dimensions of the two arrays
    * according to the broadcast rule shows that they are compatible:
        * In dim 4, A has size of 1, valid
        * In dim 3, B has size of 1, valid
        * In dim 2, A has size of 1, valid
        * In dim 1, B is empty, valid
    
|                 | dim 1   | dim 2   | dim 3 | dim 4 |
|----------------:|--------:| -------:| -----:|------:|
|A      (4d array)|    8    |   1     |   6   |   1   |
|B      (3d array)|         |   7     |   1   |   5   |
|Result (4d array)|    8    |   7     |   3   |   5   |



The simplest broadcasting example occurs when an array and a scalar value are combined in an operation:

In [74]:
a = np.array([1.0,2.0,3.0])
print(a.shape)
b = 2.0
c = a * b
print(c)

(3,)
[ 2.  4.  6.]


In [54]:
a = np.array([[[3],
               [4],
               [5]],
              [[6],
               [7],
               [8]],
              [[9],
               [10],
               [11]]])
print("shape of a:", a.shape)
print(a)
b = np.array([[1, 3]])
# b = np.array([1, 2])
print("shape of b:",b.shape)
print(b)
c = a + b
print("shape of c:",c.shape)
print(c)

shape of a: (3, 3, 1)
[[[ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]]]
shape of b: (1, 2)
[[1 3]]
shape of c: (3, 3, 2)
[[[ 4  6]
  [ 5  7]
  [ 6  8]]

 [[ 7  9]
  [ 8 10]
  [ 9 11]]

 [[10 12]
  [11 13]
  [12 14]]]


(3,)
[ 2.  4.  6.]


In [59]:
from numpy import newaxis

a = np.array([0.0,10.0,20.0,30.0])
b = np.array([1.0,2.0,3.0])
print("shape of a:",a.shape)
c = a[:,newaxis] # the newaxis index operator inserts a new axis into a, making it a two-dimensional 4x1 array.
print("shape of b:",b.shape)
print("shape of c:",c.shape)

d = c + b
print("shape of d:",d.shape)
print(d)

shape of a: (4,)
shape of b: (3,)
shape of c: (4, 1)
shape of d: (4, 3)
[[  1.   2.   3.]
 [ 11.  12.  13.]
 [ 21.  22.  23.]
 [ 31.  32.  33.]]


In [70]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])

print(A)

mean = np.sum(A, axis=0)
percentage = 100 * A / mean
print(percentage)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]
[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


## Intuitive on NumPy rank 1 vector

In [78]:
a = np.random.randn(5)
print(a)
print(a.shape)

[ 0.17076311  0.09085451  0.56343682  0.34072383 -0.59966689]
(5,)


Array a is called rank 1 array in python and it is neither a row vector nor a column vector, or it can be used as either a row vector and a column vector depends on the scenario. 

This may lead to slightly non-intuitive effects


In [79]:
print(a.T)

[ 0.17076311  0.09085451  0.56343682  0.34072383 -0.59966689]


You can see that a = a.T

In [80]:
print(np.dot(a.T, a))
print(np.dot(a, a.T))

0.830568733981
0.830568733981


The inner product between a.T and a is the same as the inner product between a and a.T

One advantage of the rank 1 vector is that it may bring flexibility since it can be used as either row vector or column vector depends on spcific situation.

In [101]:
# a.shape = (3,4)
# b.shape = (4,1)

a = np.random.randn(3, 4)
b = np.random.randn(4, 1)
c = np.zeros((3, 4))

print("a =", a)
print("b =", b)
# print("c =", c)
for i in range(3):
    for j in range(4):
        c[i, j] = a[i, j] + b[j]
        
print("c =", c)

d = a + b.T
print("d = ", d)

# d = a + b # throw ValueError exception: operands could not be broadcast together with shapes (3,4) (4,1)

a = [[ 1.44430914 -0.52287877 -0.1003128   0.55392393]
 [ 0.85258098 -0.58532288 -0.45228889 -0.31760503]
 [ 0.15836844 -1.71772026 -1.04139835 -2.22386147]]
b = [[-0.45204587]
 [-0.72772358]
 [-0.73466414]
 [ 1.55442485]]
c = [[ 0.99226327 -1.25060235 -0.83497693  2.10834878]
 [ 0.4005351  -1.31304646 -1.18695303  1.23681982]
 [-0.29367743 -2.44544384 -1.77606249 -0.66943662]]
d =  [[ 0.99226327 -1.25060235 -0.83497693  2.10834878]
 [ 0.4005351  -1.31304646 -1.18695303  1.23681982]
 [-0.29367743 -2.44544384 -1.77606249 -0.66943662]]


In [102]:
a = np.random.randn(3, 4)
b = np.random.randn(4)
c = np.zeros((3, 4))

print("a =", a)
print("b =", b)
for i in range(3):
    for j in range(4):
        c[i, j] = a[i, j] + b[j]
        
print("c =", c)

d = a + b
print("d = ", d)

a = [[-0.01899029 -0.71658135  0.9013266   0.83339728]
 [-1.24828846  0.20377194 -0.2192503  -1.92778151]
 [-1.32561916  0.98484126 -1.28973242 -0.32129865]]
b = [-1.12336554  1.34084076  0.13442701  0.46413503]
c = [[-1.14235583  0.62425942  1.0357536   1.29753231]
 [-2.371654    1.5446127  -0.0848233  -1.46364647]
 [-2.4489847   2.32568203 -1.15530542  0.14283638]]
d =  [[-1.14235583  0.62425942  1.0357536   1.29753231]
 [-2.371654    1.5446127  -0.0848233  -1.46364647]
 [-2.4489847   2.32568203 -1.15530542  0.14283638]]


However, the rank 1 vector may cause hard-to-debug bugs

One suggestion is that you can explicitly define whether it is a row vector or column vector when you are creating a vector.

In [103]:
a = np.random.randn(5, 1)
print("a =", a)
print("a transpose =", a.T)
print("outter proudct =",np.dot(a, a.T))

a = [[-0.9805898 ]
 [-0.16078553]
 [ 0.41321247]
 [-0.18559169]
 [ 0.53171361]]
a transpose = [[-0.9805898  -0.16078553  0.41321247 -0.18559169  0.53171361]]
outter proudct = [[ 0.96155635  0.15766465 -0.40519193  0.18198932 -0.52139295]
 [ 0.15766465  0.02585199 -0.06643859  0.02984046 -0.08549186]
 [-0.40519193 -0.06643859  0.17074455 -0.0766888   0.2197107 ]
 [ 0.18198932  0.02984046 -0.0766888   0.03444428 -0.09868163]
 [-0.52139295 -0.08549186  0.2197107  -0.09868163  0.28271937]]


## -= operators with numpy


When v is a slice, then v -= X and v = v - X produce very different results. 
* When use v -= 1 updates the slice, and therefore the array that it views, in-place,

In [106]:
x = np.arange(6)
print(x)
v = x[1:4]
print(v)
v-=1
print(v)
print(x)

[0 1 2 3 4 5]
[1 2 3]
[0 1 2]
[0 0 1 2 4 5]


* where v = v - 1 resets the variable v while leaving x untouched.

In [107]:
x = np.arange(6)
print(x)
v = x[1:4]
print(v)
v = v - 1
print(v)
print(x)

[0 1 2 3 4 5]
[1 2 3]
[0 1 2]
[0 1 2 3 4 5]


To obtain the result of modification in-place without using -=, we have have to do

In [109]:
x = np.arange(6)
print(x)
v = x[1:4]
print(v)
v[:] = v - 1
print(v)
print(x)

[0 1 2 3 4 5]
[1 2 3]
[0 1 2]
[0 0 1 2 4 5]


## Reshape

In [3]:
data = [1]
myarray = np.asarray(data)

print(data)
print(myarray)

newarr = myarray.reshape(1, -1)
print(newarr)
print(newarr.shape)

[1]
[1]
[[1]]
(1, 1)


## Numpy Documentation

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](https://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

## Reference:

1. [Stanford cs231n numpy tutorial](http://cs231n.github.io/python-numpy-tutorial/#numpy)
2. [Array broadcasting in numpy](http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc)
3. [Numpy reference](https://docs.scipy.org/doc/numpy/reference/)